"""add sharing tables and owner_id

Revision ID: 0ec6db43de91
Revises: a74815ba306e
Create Date: 2026-02-11 23:10:33.337095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ec6db43de91'
down_revision: Union[str, None] = 'a74815ba306e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder_shares',
    sa.Column('folder_id', sa.UUID(), nullable=False),
    sa.Column('shared_with_id', sa.UUID(), nullable=False),
    sa.Column('shared_by_id', sa.UUID(), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shared_with_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folder_id', 'shared_with_id', name='uq_folder_share')
    )
    op.create_table('file_shares',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('shared_with_id', sa.UUID(), nullable=False),
    sa.Column('shared_by_id', sa.UUID(), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shared_with_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'shared_with_id', name='uq_file_share')
    )
    op.add_column('files', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'files', 'users', ['owner_id'], ['id'])
    op.add_column('folders', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'folders', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.drop_column('folders', 'owner_id')
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'owner_id')
    op.drop_table('file_shares')
    op.drop_table('folder_shares')
    # ### end Alembic commands ###
