"""add_is_favorite_to_files_and_folders

Revision ID: a0614739d703
Revises: 0ec6db43de91
Create Date: 2026-02-12 11:59:27.017909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0614739d703'
down_revision: Union[str, None] = '0ec6db43de91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('is_favorite', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('folders', sa.Column('is_favorite', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folders', 'is_favorite')
    op.drop_column('files', 'is_favorite')
    # ### end Alembic commands ###
