"""add anthropic_api_key to users

Revision ID: a74815ba306e
Revises: e967324636b7
Create Date: 2026-02-11 22:48:14.441516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a74815ba306e'
down_revision: Union[str, None] = 'e967324636b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('anthropic_api_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'anthropic_api_key')
    # ### end Alembic commands ###
